### ISSUE TITLE
Not working in 8.0.1 Wow Client

### ISSUE THREAD

**Issue by Overcon** [blooblahguy/bdUnitframes#5]
New Patch has taken it out of play.

Message: Interface\AddOns\bdCore\lib\oUF\elements\auras.lua:223: attempt to compare number with nil
Time: Wed Jul 18 05:50:24 2018
Count: 4
Stack: Interface\AddOns\bdCore\lib\oUF\elements\auras.lua:223: attempt to compare number with nil
Interface\AddOns\bdCore\lib\oUF\elements\auras.lua:223: in function <Interface\AddOns\bdCore\lib\oUF\elements\auras.lua:140>
Interface\AddOns\bdCore\lib\oUF\elements\auras.lua:279: in function <Interface\AddOns\bdCore\lib\oUF\elements\auras.lua:273>
Interface\AddOns\bdCore\lib\oUF\elements\auras.lua:408: in function `func'
Interface\AddOns\bdCore\lib\oUF\events.lua:50: in function <Interface\AddOns\bdCore\lib\oUF\events.lua:48>
(tail call): ?

**Comment by gladelynch** [comment]
Been fixed, just updating open issues. Thanks for the report!
